name: Compute PTau SHA256 and update CI

on:
  workflow_dispatch:

jobs:
  compute-checksum:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download PTau
        run: |
          set -euo pipefail
          PTAU_URL="https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_10.ptau"
          echo "Downloading $PTAU_URL"
          curl -fsSL -o powersOfTau28_hez_final_10.ptau "$PTAU_URL"

      - name: Compute SHA256
        id: hash
        run: |
          sha=$(sha256sum powersOfTau28_hez_final_10.ptau | awk '{print $1}')
          echo "sha=$sha" >> $GITHUB_OUTPUT

      - name: Update ci/run_e2e.sh with checksum
        run: |
          set -euo pipefail
          sha="${{ steps.hash.outputs.sha }}"
          echo "Updating ci/run_e2e.sh with computed SHA256: $sha"
          perl -0777 -pe "s/EXPECTED_SHA256=\"REPLACE_WITH_TRUSTED_SHA256\"/EXPECTED_SHA256=\"$sha\"/s" -i ci/run_e2e.sh
          git config user.name "actions-bot"
          git config user.email "actions@users.noreply.github.com"
          git add ci/run_e2e.sh
          git commit -m "ci: set PTau checksum via workflow" || echo "no changes to commit"
          git push

      - name: Output
        run: |
          echo "Computed PTAU sha: ${{ steps.hash.outputs.sha }}"
